title = "Western Canadian Blacksmiths Guild"
baseURL = "https://albertablacksmiths.ca/"
theme = "ananke"
resourceDir = "resources"
Description = "Alberta Blacksmith Association promotes blacksmithing in Alberta through events, education, and community for all skill levels."

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'

canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

[services.googleAnalytics]
id = 'G-Y7LW4FSLV9'

[pagination]
pagerSize = 50 # this is set low for demonstrating with dummy content. Set to a higher number

[languages.en]
contentDir = "content"
languageCode = 'en-US'
weight = 1
title = "WCBG"
# languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = "favicon.ico"
site_logo = "images/WCBGLOGOSMall.png"
description = "Alberta Blacksmith Association promotes blacksmithing in Alberta through events, education, and community for all skill levels."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-dark-gray"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-70"
recent_posts_number = 3

[params.ananke.social]
  icon_path = 'ananke/socials/%s.svg'

  [params.ananke.social.instagram]
    username = 'westerncanadianblacksmiths'

  [params.ananke.social.facebook]
    username = 'WCBGalberta'

  [params.ananke.social.follow]
    networks = ['facebook', 'instagram']

  [params.ananke.social.github]
    username = 'sedward5'

  [params.ananke.social.linkedin]
    username = 'sedward5'

  [[params.ananke.social.networks]]
    color = '#1185fe'
    icon = 'bluesky'
    label = 'Bluesky'
    link = 'https://bsky.app/intent/compose'
    profile = 'https://bsky.app/profile/%s'
    slug = 'bluesky'

    [params.ananke.social.networks.particles]
      text = 'permalink'

  [[params.ananke.social.networks]]
    icon = 'envelope'
    label = 'Email'
    link = 'mailto:'
    slug = 'email'

    [params.ananke.social.networks.particles]
      body = 'permalink'
      subject = 'title'

  [[params.ananke.social.networks]]
    color = '#3b5998'
    icon = 'facebook'
    label = 'Facebook'
    link = 'https://facebook.com/sharer/sharer.php'
    profile = 'https://www.facebook.com/%s'
    slug = 'facebook'

    [params.ananke.social.networks.particles]
      u = 'permalink'

  [[params.ananke.social.networks]]
    color = '#e1306c'
    icon = 'instagram'
    label = 'Instagram'
    profile = 'https://www.instagram.com/%s/'
    slug = 'instagram'



[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "events"
    name = "Events"
    url = "/events/"
    weight = 2

  [[menu.main]]
    identifier = "membership"
    name = "Membership"
    url = "/membership/"
    weight = 3

  [[menu.main]]
    identifier = "info"
    name = "Info"
    url = "/info/"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 5
    
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 6