title = "Notre-Dame de Paris"
baseURL = "https://graemeaj.github.io/HugoAlbertaBlacksmiths/"
theme = "ananke"
resourceDir = "resources"

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'

canonifyURLs = true

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 16 # this is set low for demonstrating with dummy content. Set to a higher number

[languages.en]
contentDir = "content"
languageCode = 'en-US'
weight = 1
title = "WCBG"
# languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = "favicon.ico"
site_logo = "images/WCBGLOGOSMall.png"
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-dark-gray"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-70"
recent_posts_number = 3

[params.ananke.social.share]
networks = [
  "email",
  "facebook",
  "instagram"
]

[params.ananke.social.follow]
networks = [
  "facebook",
  "instagram"
]

[params.ananke.social.facebook]
profilelink = "https://www.facebook.com/WCBGalberta"

[params.ananke.social.instagram]
username = "westerncanadianblacksmiths"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "events"
    name = "Events"
    url = "/events/"
    weight = 2

  [[menu.main]]
    identifier = "membership"
    name = "Membership"
    url = "/membership/"
    weight = 3

  [[menu.main]]
    identifier = "info"
    name = "Info"
    url = "/info/"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 5
    
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 6